const RECIPES = [
  {id:"r1",  t:"Spicy Tomato Pasta",   d:"Hurtig pasta med tomat og chili.",              time:"25 min",  diff:"Easy",   tags:["Italian","Quick"],       ing:["Pasta","Tomater","Hvidløg","Chili","Olivenolie","Parmesan","Basilikum"], hue:0},
  {id:"r2",  t:"Red Pepper Shakshuka", d:"Æg i krydret tomat- og pebersauce.",            time:"35 min",  diff:"Medium", tags:["One-pan","Vegetarian"],  ing:["Æg","Peberfrugt","Tomater","Løg","Spidskommen","Paprika"], hue:18},
  {id:"r3",  t:"Bibimbap Bowl",        d:"Risret med grøntsager og gochujang.",           time:"45 min",  diff:"Medium", tags:["Bowl","Umami"],          ing:["Ris","Spinat","Gulerod","Svampe","Æg","Gochujang"], hue:330},
  {id:"r4",  t:"Crispy Chicken Wrap",  d:"Sprød chicken wrap med røget sauce.",           time:"30 min",  diff:"Easy",   tags:["Lunch","Comfort"],       ing:["Kylling","Tortillas","Salat","Yoghurt","Paprika"], hue:350},
  {id:"r5",  t:"Garlic Butter Salmon", d:"Laks stegt i hvidløgssmør.",                    time:"20 min",  diff:"Easy",   tags:["Quick","Protein"],       ing:["Laks","Smør","Hvidløg","Citron","Persille"], hue:8},
  {id:"r6",  t:"Smoky Bean Tacos",     d:"Hurtige tacos med bønner og lime.",             time:"20 min",  diff:"Easy",   tags:["Vegetarian","Quick"],    ing:["Bønner","Tacoskaller","Løg","Lime","Spidskommen"], hue:25},
  {id:"r7",  t:"Classic Burger",       d:"Saftig burger med løg og ost.",                 time:"35 min",  diff:"Medium", tags:["Dinner","Comfort"],      ing:["Oksekød","Boller","Løg","Cheddar","Pickles"], hue:345},
  {id:"r8",  t:"Ramen-Style Soup",     d:"Varm nudelsuppe med toppings.",                 time:"30 min",  diff:"Medium", tags:["Soup","Comfort"],        ing:["Nudler","Bouillon","Soja","Ingefær","Æg"], hue:5},
  {id:"r9",  t:"Chocolate Mug Cake",   d:"Varm chokoladekage på få minutter.",            time:"8 min",   diff:"Easy",   tags:["Dessert","Quick"],       ing:["Mel","Kakao","Sukker","Mælk","Smør"], hue:340},
  {id:"r10", t:"Caesar Salad",         d:"Sprød salat med klassisk dressing.",            time:"15 min",  diff:"Easy",   tags:["Salad","Classic"],       ing:["Romaine","Croutoner","Parmesan","Hvidløg","Citron"], hue:12},
  {id:"r11", t:"Paneer Tikka Skillet", d:"Krydret paneer med peberfrugt.",                time:"25 min",  diff:"Medium", tags:["Vegetarian","Spiced"],    ing:["Paneer","Peberfrugt","Løg","Yoghurt","Krydderier"], hue:20},
  {id:"r12", t:"Overnight Oats",       d:"Kolde cremede havregryn med bær.",              time:"10 min",  diff:"Easy",   tags:["Breakfast","No-cook"],   ing:["Havregryn","Mælk","Yoghurt","Bær","Honning"], hue:0},
];

const INSP = ["r1","r2","r5","r6","r9","r10","r12","r8"];
const TOP10 = ["r5","r1","r8","r3","r6","r2","r9","r7","r10","r11"];

const LS_RATE = "ff_rate";
const LS_LIST = "ff_list";
const LS_LANG = "ff_lang";
const LS_USERS = "ff_users";
const LS_ACTIVE_USER = "ff_active_user";

const TEXT = {
  da: {
    chooseTitle: "Vælg en sektion",
    inspiration: "Inspiration",
    inspirationSub: "Idéer til at komme i gang",
    top10: "Top 10",
    top10Sub: "Mest populære opskrifter",
    yourchoice: "Your Choice",
    yourchoiceSub: "Dine gemte opskrifter",
    frontText: "Klar til at finde en opskrift? Søg efter navn eller ingredienser.",
    frontPlaceholder: "Søg efter opskrifter...",
    frontButton: "Søg",
    sectionPlaceholder: "Søg i denne sektion...",
    clear: "Clear",
    preview: "Preview:",
    previewDefault: "Hold musen over en opskrift for at se preview",
    noResults: "Ingen opskrifter fundet.",
    back: "← Tilbage til forsiden",
    ingredients: "Ingredienser",
    rating: "Vurdering",
    noRating: "Ingen vurdering endnu.",
    yourRating: "Din vurdering:",
    addChoice: "+ Your Choice",
    removeChoice: "✓ In Your Choice (Remove)",
    noSavedTitle: "Ingen gemte opskrifter",
    noSavedDesc: "Gem en opskrift for at se den her.",
    searchResults: "Søgeresultater",
    noSearchTitle: "Ingen resultater",
    noSearchDesc: "Prøv at søge efter en anden opskrift eller ingrediens.",
    userLoggedOut: "Ikke logget ind",
    userLoggedIn: "Logget ind som",
    email: "E-mail",
    password: "Adgangskode",
    createProfile: "Opret profil",
    login: "Log ind",
    logout: "Log ud",
    createSuccess: "Profil oprettet.",
    loginSuccess: "Du er nu logget ind.",
    loginFail: "Forkert e-mail eller adgangskode.",
    createFail: "E-mail findes allerede.",
    fillFields: "Udfyld e-mail og adgangskode.",
    loggedOutMessage: "Du er logget ud.",
    recipeNotFound: "Opskrift ikke fundet",
    recipeMissingText: "Denne opskrift findes ikke."
  },
  en: {
    chooseTitle: "Choose a section",
    inspiration: "Inspiration",
    inspirationSub: "Ideas to get started",
    top10: "Top 10",
    top10Sub: "Most popular recipes",
    yourchoice: "Your Choice",
    yourchoiceSub: "Your saved recipes",
    frontText: "Ready to find a recipe? Search by name or ingredients.",
    frontPlaceholder: "Search recipes...",
    frontButton: "Search",
    sectionPlaceholder: "Search in this section...",
    clear: "Clear",
    preview: "Preview:",
    previewDefault: "Hover a recipe to preview it",
    noResults: "No recipes found.",
    back: "← Back to front page",
    ingredients: "Ingredients",
    rating: "Rating",
    noRating: "No rating yet.",
    yourRating: "Your rating:",
    addChoice: "+ Your Choice",
    removeChoice: "✓ In Your Choice (Remove)",
    noSavedTitle: "No saved recipes",
    noSavedDesc: "Save a recipe to see it here.",
    searchResults: "Search Results",
    noSearchTitle: "No results",
    noSearchDesc: "Try searching for another recipe or ingredient.",
    userLoggedOut: "Not logged in",
    userLoggedIn: "Logged in as",
    email: "E-mail",
    password: "Password",
    createProfile: "Create profile",
    login: "Log in",
    logout: "Log out",
    createSuccess: "Profile created.",
    loginSuccess: "You are now logged in.",
    loginFail: "Wrong e-mail or password.",
    createFail: "E-mail already exists.",
    fillFields: "Fill in e-mail and password.",
    loggedOutMessage: "You are logged out.",
    recipeNotFound: "Recipe not found",
    recipeMissingText: "This recipe does not exist."
  }
};
